	detour((void *)0x3814e0, (void *)hook_calloc); //callocref
	detour((void *)0x3814fa, (void *)hook_calloc); //callocref
	detour((void *)0x38151a, (void *)hook_calloc); //callocref
	detour((void *)0x665d7a, (void *)hook_calloc); //callocref
	detour((void *)0x6d93a, (void *)hook_malloc); //mallocref
	detour((void *)0x6f20e, (void *)hook_malloc); //mallocref
	detour((void *)0xe38e4, (void *)hook_malloc); //mallocref
	detour((void *)0x13a8c6, (void *)hook_malloc); //mallocref
	detour((void *)0x13aa40, (void *)hook_malloc); //mallocref
	detour((void *)0x169c7c, (void *)hook_malloc); //mallocref
	detour((void *)0x169cf8, (void *)hook_malloc); //mallocref
	detour((void *)0x169d66, (void *)hook_malloc); //mallocref
	detour((void *)0x2f845c, (void *)hook_malloc); //mallocref
	detour((void *)0x2f853e, (void *)hook_malloc); //mallocref
	detour((void *)0x2f8626, (void *)hook_malloc); //mallocref
	detour((void *)0x311680, (void *)hook_malloc); //mallocref
	detour((void *)0x37f746, (void *)hook_malloc); //mallocref
	detour((void *)0x3f26ca, (void *)hook_malloc); //mallocref
	detour((void *)0x4b9c2e, (void *)hook_malloc); //mallocref
	detour((void *)0x57d2aa, (void *)hook_malloc); //mallocref
	detour((void *)0x584884, (void *)hook_malloc); //mallocref
	detour((void *)0x58ab2e, (void *)hook_malloc); //mallocref
	detour((void *)0x58ab3c, (void *)hook_malloc); //mallocref
	detour((void *)0x60ae5a, (void *)hook_malloc); //mallocref
	detour((void *)0x60aeb2, (void *)hook_malloc); //mallocref
	detour((void *)0x60b1e4, (void *)hook_malloc); //mallocref
	detour((void *)0x60c44e, (void *)hook_malloc); //mallocref
	detour((void *)0x60c718, (void *)hook_malloc); //mallocref
	detour((void *)0x60d8f8, (void *)hook_malloc); //mallocref
	detour((void *)0x60e4f0, (void *)hook_malloc); //mallocref
	detour((void *)0x60e506, (void *)hook_malloc); //mallocref
	detour((void *)0x60e516, (void *)hook_malloc); //mallocref
	detour((void *)0x60e854, (void *)hook_malloc); //mallocref
	detour((void *)0x60e86c, (void *)hook_malloc); //mallocref
	detour((void *)0x60e928, (void *)hook_malloc); //mallocref
	detour((void *)0x60ee28, (void *)hook_malloc); //mallocref
	detour((void *)0x60ee30, (void *)hook_malloc); //mallocref
	detour((void *)0x60ee38, (void *)hook_malloc); //mallocref
	detour((void *)0x60ee72, (void *)hook_malloc); //mallocref
	detour((void *)0x60efae, (void *)hook_malloc); //mallocref
	detour((void *)0x60efde, (void *)hook_malloc); //mallocref
	detour((void *)0x60f072, (void *)hook_malloc); //mallocref
	detour((void *)0x60f144, (void *)hook_malloc); //mallocref
	detour((void *)0x60f1a0, (void *)hook_malloc); //mallocref
	detour((void *)0x60f23e, (void *)hook_malloc); //mallocref
	detour((void *)0x60f30a, (void *)hook_malloc); //mallocref
	detour((void *)0x60f40a, (void *)hook_malloc); //mallocref
	detour((void *)0x661cba, (void *)hook_malloc); //mallocref
	detour((void *)0x1670b6, (void *)hook_malloc); //j_mallocref
	detour((void *)0x1670c6, (void *)hook_malloc); //j_mallocref
	detour((void *)0x17cf60, (void *)hook_malloc); //j_mallocref
	detour((void *)0x3116ca, (void *)hook_malloc); //j_mallocref
	detour((void *)0x4b97f6, (void *)hook_malloc); //j_mallocref GameObjectManager
	detour((void *)0x151ab4, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x151d94, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x151e5e, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x151fcc, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x15211a, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x15223e, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x152312, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x15253a, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x1525c8, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x15261c, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x15266a, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x1526c2, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x152716, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x1527ce, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x15288e, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x15291c, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x152970, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x1529be, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x152a16, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x152a6a, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x152b22, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x152bb4, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x15303e, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x153470, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x1534e8, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x1535aa, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x153616, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x153650, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x153e00, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x1540c0, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x154284, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x154794, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x1548d4, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x154a70, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x154c96, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x154cc2, (void *)hook_malloc); //j_j_mallocref
	detour((void *)0x61a0c8, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61b12e, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61bf3c, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61c856, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61c888, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61ca40, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61ca66, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61cc64, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61cd86, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61cdc2, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61cdfa, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61ce3e, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61cea6, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61cf0e, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61d27c, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61d2c2, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61d2fe, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61d972, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61dab6, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61daf4, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61de0a, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61e24c, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61e38e, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61e446, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61e466, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61e4fe, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61e5f0, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61e698, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61eafc, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61eb5c, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61eba4, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61f584, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61f5f8, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61f666, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61f81c, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61f8de, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x61f908, (void *)hook_malloc); //j_j_mallocref0
	detour((void *)0x618752, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x61875c, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x620c2e, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x621dc0, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x6228d6, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x62293e, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x626a12, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x626b28, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x629bce, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x629c1a, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x629fc6, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x62a010, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x62ef94, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x62f130, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x62f78c, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x62f796, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x62f7bc, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x62f7c8, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x62f7d4, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x631572, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x6328e0, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x632d86, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x632eba, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x633034, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x63312a, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x63331c, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x634e1a, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x634e24, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x635366, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x635370, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x63539a, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x6353a6, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x6353b2, (void *)hook_malloc); //j_j_mallocref1
	detour((void *)0x620b22, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x620b54, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x620fd6, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62106c, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x621142, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x621156, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62116c, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x6212f8, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x621364, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62149e, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x621506, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x621736, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x6217b0, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62196e, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x6222ce, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x6224ba, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x622564, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62288c, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x6229c0, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x622d2a, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x622d44, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62304a, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x623b06, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62411e, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x624166, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x6241a2, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x6241ea, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x624226, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62427e, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x6242e2, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62432e, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62437e, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x6243ca, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62441a, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x624466, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x6244b4, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x624864, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x6248d2, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x6258f8, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x625ef8, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x626082, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x6260de, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62616e, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x6262bc, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x626a6c, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x626b84, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x626bac, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x627678, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x6278a2, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x6279c0, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x627b5c, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x627f32, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x627fa0, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x628348, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x6298e8, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x629ae2, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x629b24, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x629b7c, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x629e72, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x629f12, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x629f6c, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62a350, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62a420, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62a46c, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62a5a0, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62a6da, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62a75a, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62a846, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62a8ae, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62a94e, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62a9e6, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62aaf6, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62ac04, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62ade4, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62ae80, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62aecc, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62af24, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62af4c, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62afb4, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62aff0, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62b10e, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62b178, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62b1fc, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62b664, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62b6fe, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62b77a, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62b8b2, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62b95a, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62b9aa, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62ba18, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62bf54, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62c06a, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62c24c, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62c422, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62c9cc, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62cb14, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62d000, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62d0fa, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62d1ae, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62d262, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62d916, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62d992, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62e03a, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62e1b8, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62e4e6, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62e62e, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62e6c6, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62e89e, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62e92e, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62e98a, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62ea6c, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62ead8, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62eb78, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62ebf4, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62efa8, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62f06c, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62f2fc, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62f454, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x62f5ac, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x630d5e, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x632364, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x632458, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x6325c8, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x632788, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x63290a, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x632992, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x632a00, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x632b16, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x632b48, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x632b8e, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x632ba4, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x632bb8, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x632bf8, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x632c0e, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x632c26, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x632c66, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x632c7c, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x632e14, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x633808, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x6338dc, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x63399a, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x6339cc, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x633ad2, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x633b02, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x633c48, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x633d14, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x633d4c, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x633e54, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x633e8a, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x633f8c, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x634170, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x63427c, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x63493a, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x6349b6, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x634a74, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x634bae, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x634ca0, (void *)hook_malloc); //j_j_mallocref2
	detour((void *)0x611234, (void *)hook_malloc); //j_j_mallocref3
	detour((void *)0x615374, (void *)hook_malloc); //j_j_mallocref3
	detour((void *)0x615be6, (void *)hook_malloc); //j_j_mallocref3
	detour((void *)0x616d54, (void *)hook_malloc); //j_j_mallocref3
	detour((void *)0x2f8490, (void *)hook_realloc); //reallocref
	detour((void *)0x381550, (void *)hook_realloc); //reallocref
	detour((void *)0x381564, (void *)hook_realloc); //reallocref
	detour((void *)0x381574, (void *)hook_realloc); //reallocref
	detour((void *)0x60e642, (void *)hook_realloc); //reallocref
	detour((void *)0x60e656, (void *)hook_realloc); //reallocref
	detour((void *)0x60ec02, (void *)hook_realloc); //reallocref
	detour((void *)0x2f84e2, (void *)hook_realloc); //j_reallocref
	detour((void *)0x3116e8, (void *)hook_realloc); //j_reallocref
	detour((void *)0x152f44, (void *)hook_realloc); //j_j_reallocref
	detour((void *)0x152fd8, (void *)hook_realloc); //j_j_reallocref
	detour((void *)0x37f776, (void *)hook_realloc); //reallocfref
