include theos/makefiles/common.mk

TWEAK_NAME = memoryedit
memoryedit_FILES = Tweak.xm
memoryedit_FRAMEWORKS = UIKit

memoryedit_LDFLAGS = -read_only_relocs suppress

include $(THEOS_MAKE_PATH)/tweak.mk


